---
title: "STIN100 Datasett 3: Når får barn en tarmflora som ligner på den vi ser hos voksne?"
author: "Benjamin Johan Madsen & Aksel Vardeberg Skeie"
date: "29 oktober 2018"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
#https://github.com/Baconscott/Eksamen.git
#Dette er linken til Github om vi trenger den
```

##1.2 Forberedelser


Følgende pakker er blitt lastet ned: ```tidyverse, ggplot2, gplots```

```{r, include = FALSE}
library(tidyverse) 
library(gplots) 
library(readxl) 
```

##2.1 Last inn dataene
```{r, Include = FALSE}
data <- read_excel("mor_barn_tid_tarmflora.xlsx") #Disse dataene er normalisert og dette er en tibbel 
```

Vi ser at i datasette er det 1124 rader  
```{r}
nrow(data)
```

og 1277 kolonner.
```{r}
ncol(data)
```

##2.2

Tabell 1: gir en oppsumering av kolonne 2:6
```{r}
summary(data[,2:6])
```

Fra tabell en ser vi at vi har følgende:

- Variabler: ```Motherchild```
- Observasjone: ```Timepoint```
- Verdier: ```Methanobrevibacter, Clostridiales, Dialister ```

##2.3
Videre skal vi sortere variablene i kolonnene ```Timepoint``` og ```Motherchild```. Vi ønsker de en en spesiel rekkefølge og den presiserer vi i koden under.
```{r}
data$Timepoint <- as.factor(data$Timepoint)
data$Timepoint <- factor(data$Timepoint, levels = c("Pregnancy", "10days",  "3months", "1year", "2years"))

data$MotherChild <- as.factor(data$MotherChild)
data$MotherChild <- factor(data$MotherChild, levels = c("mother", "child"))

levels(data$MotherChild)
levels(data$Timepoint)
```
